CREATE TABLE "products" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name_product" varchar,
  "weight_product" integer,
  "product_expiration_date" date,
  "calories_product" integer,
  "wholesale_price_product" integer
);

CREATE TABLE "compound_products" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" integer,
  "quantity" integer
);

CREATE TABLE "ingredients" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "compound_id" integer,
  "product_expiration_date" date,
  "calories_product" integer,
  "price" integer
);

CREATE TABLE "procurement" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ingredient_id" integer,
  "quantity" integer,
  "procurement_date" date,
  "added" bool
);

CREATE TABLE "fabric" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" integer,
  "quantity" integer,
  "date_manufacture" date,
  "defective" integer
);

CREATE TABLE "implementation" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" integer,
  "quantity" integer,
  "date_manufacture" date
);

ALTER TABLE "compound_products" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "ingredients" ADD FOREIGN KEY ("compound_id") REFERENCES "compound_products" ("id");

ALTER TABLE "procurement" ADD FOREIGN KEY ("ingredient_id") REFERENCES "ingredients" ("id");

ALTER TABLE "fabric" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "implementation" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");
